[pytest]
markers =
    integration: testes que exigem serviços externos
    e2e: testes end-to-end completos que exigem um ambiente real
asyncio_mode = strict
env =
    TESTING=1
    HWA_HOSTNAME=test_host
    HWA_PORT=12345
    HWA_USERNAME=test_user
    HWA_PASSWORD=test_password
