"""Add index to timestamp column on job history table

Revision ID: 329c94f2fc31
Revises: 0bf106a88593
Create Date: 2025-09-07 23:07:03.244539

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "329c94f2fc31"
down_revision: Union[str, Sequence[str], None] = "0bf106a88593"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_job_status_history_timestamp"),
        "job_status_history",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_job_status_history_timestamp"), table_name="job_status_history"
    )
    # ### end Alembic commands ###
