name: CI Pipeline

on:
  push:
    branches: [ main, master, bugfix/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        pip install -e ".[dev]"
        npm install

    - name: Run Linting and Formatting Checks
      run: |
        pre-commit run --all-files

    - name: Run Backend and Frontend Tests
      run: |
        # It's important to set the python path for the tests
        # This batch includes the playwright tests
        PYTHONPATH=. pytest tests/test_app.py tests/test_core.py tests/test_frontend.py

    - name: Run Monitoring and ML Tests
      run: |
        # This batch runs the tests that conflict with playwright's event loop
        PYTHONPATH=. pytest tests/test_monitoring.py tests/test_ml.py
